# Generated by Django 4.1.4 on 2023-01-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='user_id',
            new_name='user',
        ),
    ]
